import type { Locale } from "@/lib/i18n";

const ru = {
  meta: {
    title: "Savdo CRM — демо CRM-системы для бизнеса",
    description: "Демо CRM от CaravanHouse: дашборд с аналитикой, воронка сделок с перетаскиванием, клиенты, задачи и заявки из Telegram-бота в реальном времени.",
  },
  demo: { text: "Демо CRM от CaravanHouse — компания и данные вымышленные, всё хранится только в вашем браузере.", cta: "Заказать такую CRM" },
  workspace: "Dekor Mebel",
  role: "Руководитель продаж",
  nav: { dashboard: "Дашборд", pipeline: "Сделки", clients: "Клиенты", tasks: "Задачи" },
  search: "Поиск по сделкам и клиентам…",
  newDeal: "Новая сделка",
  reset: "Сбросить демо",
  resetDone: "Демо-данные восстановлены",
  langLabel: "Язык",
  currency: "сум",
  mln: "млн",
  stages: { new: "Новая заявка", qualified: "Замер", proposal: "КП отправлено", payment: "Ожидает оплату", won: "Успешно", lost: "Отказ" },
  sources: { telegram: "Telegram-бот", instagram: "Instagram", site: "Сайт", call: "Звонок", referral: "Рекомендация" },
  dashboard: {
    hello: "Добрый день",
    subtitle: "Вот что происходит с продажами сегодня",
    revenue: "Выручка за месяц",
    pipeline: "В работе",
    conversion: "Конверсия",
    avgDeal: "Средний чек",
    vsLast: "к прошлому месяцу",
    deals: "сделок",
    revenueChart: "Выручка по месяцам",
    sourcesChart: "Откуда приходят клиенты",
    funnel: "Воронка продаж",
    todayTasks: "Задачи на сегодня",
    activity: "Последние события",
    allTasks: "Все задачи",
    noTasks: "На сегодня всё сделано 🎉",
  },
  pipeline: {
    title: "Сделки",
    hint: "Перетащите карточку в другой этап — или откройте сделку и смените этап там.",
    empty: "Пусто",
    moveTo: "Перенести в этап",
  },
  clients: {
    title: "Клиенты",
    search: "Имя или телефон…",
    allSources: "Все источники",
    name: "Клиент",
    phone: "Телефон",
    source: "Источник",
    deals: "Сделки",
    total: "Сумма сделок",
    empty: "Клиенты не найдены",
  },
  tasks: {
    title: "Задачи",
    overdue: "Просрочено",
    today: "Сегодня",
    tomorrow: "Завтра",
    later: "Позже",
    add: "Новая задача на сегодня…",
    addButton: "Добавить",
    done: "Выполнено",
  },
  deal: {
    client: "Клиент",
    amount: "Сумма",
    stage: "Этап",
    source: "Источник",
    manager: "Менеджер",
    created: "Создана",
    history: "История",
    note: "Заметка, итог звонка…",
    addNote: "Сохранить",
    call: "Позвонить",
    write: "Telegram",
    won: "Сделка успешна",
    lost: "Отказ",
    close: "Закрыть",
    stageChanged: "Этап изменён",
  },
  form: {
    title: "Новая сделка",
    name: "Имя клиента или компания",
    phone: "Телефон",
    what: "Что нужно",
    amount: "Сумма, сум",
    source: "Источник",
    manager: "Менеджер",
    save: "Создать сделку",
    cancel: "Отмена",
    required: "Заполните имя, телефон и задачу",
  },
  live: { title: "Новая заявка", from: "из", open: "Открыть" },
  time: { now: "только что", min: "мин назад", hours: "ч назад", yesterday: "вчера", days: "дн назад" },
  months: ["янв", "фев", "мар", "апр", "май", "июн", "июл", "авг", "сен", "окт", "ноя", "дек"],
};

export type UI = typeof ru;

const uz: UI = {
  meta: {
    title: "Savdo CRM — biznes uchun CRM tizimi demosi",
    description: "CaravanHouse tayyorlagan CRM demosi: tahliliy dashbord, sudrab koʻchiriladigan bitimlar voronkasi, mijozlar, vazifalar va Telegram-botdan real vaqtda keladigan arizalar.",
  },
  demo: { text: "CaravanHouse CRM demosi — kompaniya va maʼlumotlar oʻylab topilgan, hammasi faqat brauzeringizda saqlanadi.", cta: "Shunday CRM buyurtma qilish" },
  workspace: "Dekor Mebel",
  role: "Savdo boʻlimi rahbari",
  nav: { dashboard: "Dashbord", pipeline: "Bitimlar", clients: "Mijozlar", tasks: "Vazifalar" },
  search: "Bitim va mijozlar boʻyicha qidiruv…",
  newDeal: "Yangi bitim",
  reset: "Demoni tiklash",
  resetDone: "Demo maʼlumotlar tiklandi",
  langLabel: "Til",
  currency: "soʻm",
  mln: "mln",
  stages: { new: "Yangi ariza", qualified: "Oʻlchov", proposal: "Taklif yuborildi", payment: "Toʻlov kutilmoqda", won: "Muvaffaqiyatli", lost: "Rad etildi" },
  sources: { telegram: "Telegram-bot", instagram: "Instagram", site: "Sayt", call: "Qoʻngʻiroq", referral: "Tavsiya" },
  dashboard: {
    hello: "Xayrli kun",
    subtitle: "Bugun savdoda nimalar boʻlyapti",
    revenue: "Oylik tushum",
    pipeline: "Jarayonda",
    conversion: "Konversiya",
    avgDeal: "Oʻrtacha chek",
    vsLast: "oʻtgan oyga nisbatan",
    deals: "bitim",
    revenueChart: "Oylar boʻyicha tushum",
    sourcesChart: "Mijozlar qayerdan keladi",
    funnel: "Savdo voronkasi",
    todayTasks: "Bugungi vazifalar",
    activity: "Soʻnggi voqealar",
    allTasks: "Barcha vazifalar",
    noTasks: "Bugungi hamma ish bajarildi 🎉",
  },
  pipeline: {
    title: "Bitimlar",
    hint: "Kartochkani boshqa bosqichga sudrang — yoki bitimni ochib, bosqichni oʻsha yerda oʻzgartiring.",
    empty: "Boʻsh",
    moveTo: "Bosqichga koʻchirish",
  },
  clients: {
    title: "Mijozlar",
    search: "Ism yoki telefon…",
    allSources: "Barcha manbalar",
    name: "Mijoz",
    phone: "Telefon",
    source: "Manba",
    deals: "Bitimlar",
    total: "Bitimlar summasi",
    empty: "Mijozlar topilmadi",
  },
  tasks: {
    title: "Vazifalar",
    overdue: "Muddati oʻtgan",
    today: "Bugun",
    tomorrow: "Ertaga",
    later: "Keyinroq",
    add: "Bugun uchun yangi vazifa…",
    addButton: "Qoʻshish",
    done: "Bajarildi",
  },
  deal: {
    client: "Mijoz",
    amount: "Summa",
    stage: "Bosqich",
    source: "Manba",
    manager: "Menejer",
    created: "Yaratilgan",
    history: "Tarix",
    note: "Eslatma, qoʻngʻiroq natijasi…",
    addNote: "Saqlash",
    call: "Qoʻngʻiroq qilish",
    write: "Telegram",
    won: "Bitim muvaffaqiyatli",
    lost: "Rad etildi",
    close: "Yopish",
    stageChanged: "Bosqich oʻzgartirildi",
  },
  form: {
    title: "Yangi bitim",
    name: "Mijoz yoki kompaniya nomi",
    phone: "Telefon",
    what: "Nima kerak",
    amount: "Summa, soʻm",
    source: "Manba",
    manager: "Menejer",
    save: "Bitim yaratish",
    cancel: "Bekor qilish",
    required: "Ism, telefon va vazifani toʻldiring",
  },
  live: { title: "Yangi ariza", from: "manba:", open: "Ochish" },
  time: { now: "hozirgina", min: "daq oldin", hours: "soat oldin", yesterday: "kecha", days: "kun oldin" },
  months: ["yan", "fev", "mar", "apr", "may", "iyn", "iyl", "avg", "sen", "okt", "noy", "dek"],
};

const dictionaries: Record<Locale, UI> = { ru, uz };
export const getUI = (lang: Locale) => dictionaries[lang];
